[tool.poetry]
name = "backtesting"
version = "0.1.0"
description = "Backtest trading strategies in Python"
readme = "README.md"
license = "AGPL-3.0"
authors = ["Zach LÃ»ster"]
repository = "https://github.com/kernc/backtesting.py/"
documentation = "https://kernc.github.io/backtesting.py/doc/backtesting/"
homepage = "https://kernc.github.io/backtesting.py/"
keywords = [
    "algo", "algorithmic", "ashi", "backtest", "backtesting", "bitcoin", "bokeh", 
    "bonds", "candle", "candlestick", "cboe", "chart", "cme", "commodities", 
    "crash", "crypto", "currency", "doji", "drawdown", "equity", "etf", 
    "ethereum", "exchange", "finance", "financial", "forecast", "forex", 
    "fund", "futures", "fx", "fxpro", "gold", "heiken", "historical", 
    "indicator", "invest", "investing", "investment", "macd", "market", 
    "mechanical", "money", "oanda", "ohlc", "ohlcv", "order", "price", 
    "profit", "quant", "quantitative", "rsi", "silver", "simulation", 
    "stocks", "strategy", "ticker", "trader", "trading", "tradingview", "usd"
]
classifiers = [
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "Framework :: Jupyter",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Office/Business :: Financial :: Investment",
    "Topic :: Scientific/Engineering :: Visualization",
]
packages = [
    { include = "backtesting" }
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/kernc/backtesting.py/issues"

[tool.poetry.dependencies]
python = ">=3.11"
numpy = ">=2.0.0"
pandas = ">=0.3"
pandas-ta = { path = "/code/pandas-ta", develop = true}
bokeh = ">=1.4.0,!=3.0.*,!=3.2.*"

[tool.poetry.group.doc.dependencies]
pdoc3 = "*"
jupytext = ">=1.3"
nbconvert = "*"
ipykernel = "*"
jupyter_client = "*"

[tool.poetry.group.test.dependencies]
matplotlib = "*"
scikit-learn = "*"
sambo = "*"
tqdm = "*"

[tool.poetry.group.dev.dependencies]
flake8 = "*"
coverage = "*"
mypy = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

