[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=6.0"]
build-backend = "setuptools.build_meta"

[project]
name = "backtesting"
version = "0.1.0"
description = "Backtest trading strategies in Python"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "AGPL-3.0"}
authors = [
    {name = "Zach LÃ»ster"}
]
classifiers = [
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Science/Research",
    "Framework :: Jupyter",
    "License :: OSI Approved :: GNU Affero General Public License v3 or later (AGPLv3+)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Office/Business :: Financial :: Investment",
    "Topic :: Scientific/Engineering :: Visualization",
]
keywords = [
    "algo", "algorithmic", "ashi", "backtest", "backtesting", "bitcoin", "bokeh", 
    "bonds", "candle", "candlestick", "cboe", "chart", "cme", "commodities", 
    "crash", "crypto", "currency", "doji", "drawdown", "equity", "etf", 
    "ethereum", "exchange", "finance", "financial", "forecast", "forex", 
    "fund", "futures", "fx", "fxpro", "gold", "heiken", "historical", 
    "indicator", "invest", "investing", "investment", "macd", "market", 
    "mechanical", "money", "oanda", "ohlc", "ohlcv", "order", "price", 
    "profit", "quant", "quantitative", "rsi", "silver", "simulation", 
    "stocks", "strategy", "ticker", "trader", "trading", "tradingview", "usd"
]
dependencies = [
    "numpy >= 2.0.0",
    "pandas >= 0.25.0, != 0.25.0",
    "bokeh >= 1.4.0, != 3.0.*, != 3.2.*",
]

[project.urls]
Documentation = "https://kernc.github.io/backtesting.py/doc/backtesting/"
Source = "https://github.com/kernc/backtesting.py/"
Tracker = "https://github.com/kernc/backtesting.py/issues"
Homepage = "https://kernc.github.io/backtesting.py/"

[project.optional-dependencies]
doc = [
    "pdoc3",
    "jupytext >= 1.3",
    "nbconvert",
    "ipykernel",
    "jupyter_client",
]
test = [
    "matplotlib",
    "scikit-learn",
    "sambo",
    "tqdm",
]
dev = [
    "flake8",
    "coverage",
    "mypy",
]

[tool.setuptools]
packages = ["backtesting"]
include-package-data = true

[tool.setuptools_scm]
write_to = "backtesting/_version.py"

